package org.example.supplierservice.enums;

public enum OperationCategory {
    SUPPLIER_ONBOARDING,
    SUPPLIER_REGISTRATION,
    SUPPLIER_VERIFICATION,
    SUPPLIER_RISK_MANAGEMENT,
    SUPPLIER_COMPLIANCE,
    SUPPLIER_PERFORMANCE,
    SUPPLIER_AUDIT,
    SUPPLIER_DOCUMENT_MANAGEMENT,
    SUPPLIER_PORTAL,

    // Sourcing & Procurement
    SOURCING,
    RFQ_MANAGEMENT,
    RFP_MANAGEMENT,
    AUCTION_MANAGEMENT,
    CONTRACT_MANAGEMENT,
    PURCHASE_REQUISITION,
    PURCHASE_ORDER,
    PROCUREMENT_OPERATIONS,
    CATEGORY_MANAGEMENT,

    // Finance Operations
    INVOICE_MANAGEMENT,
    PAYMENT_PROCESSING,
    TAX_MANAGEMENT,
    BUDGET_MANAGEMENT,
    EXPENSE_MANAGEMENT,

    // Inventory & Logistics
    INVENTORY_MANAGEMENT,
    WAREHOUSE_MANAGEMENT,
    SHIPMENT_TRACKING,
    LOGISTICS_MANAGEMENT,
    DELIVERY_MANAGEMENT,

    // User & Access Management
    USER_MANAGEMENT,
    ROLE_MANAGEMENT,
    ACCESS_CONTROL,
    APPROVAL_WORKFLOW,

    // Compliance & Governance
    POLICY_MANAGEMENT,
    AUDIT_MANAGEMENT,
    REGULATORY_COMPLIANCE,
    SECURITY_MANAGEMENT,

    // Analytics & Reporting
    REPORTING,
    ANALYTICS,
    DASHBOARD,
    KPI_TRACKING,

    // Platform Operations
    NOTIFICATION_MANAGEMENT,
    INTEGRATION_MANAGEMENT,
    API_MANAGEMENT,
    SYSTEM_CONFIGURATION,
    TENANT_MANAGEMENT,

    // AI / Automation
    AI_AGENT,
    AUTOMATION_WORKFLOW,
    DOCUMENT_AI,
    PREDICTIVE_ANALYTICS
}
